# Introduction to NumPy

NumPy is a linear algebra library for Python!


# NumPy Arrays

NumPy arrays are the main way we will use NumPy.

NumPy arrays essentially come in two flavors: vectors and matrices.

Vectors are 1-d arrays and matrices are 2-d.

In [1]:
import numpy as np

## Creating NumPy Arrays

From a list.

In [2]:
my_list = [1, 2, 3]
my_list

[1, 2, 3]

In [3]:
arr = np.array(my_list)
arr

array([1, 2, 3])

In [4]:
my_matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
mat = np.array(my_matrix)
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in Methods

### arange

Return evenly spaced values within a given interval.

Similar to Python range().

USE SHIFT + TAB TO READ FUNCTIONS DOCUMENTATION!

In [6]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

### zeros and ones

Generate arrays of zeros or ones.

In [8]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [9]:
np.zeros((5, 5)) # (rows, columns)

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [10]:
np.ones(3)

array([ 1.,  1.,  1.])

In [11]:
np.ones((3, 3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

### linspace

Return evenly spaced numbers over a specified interval.

In [12]:
np.linspace(0, 10, 3)

array([  0.,   5.,  10.])

In [13]:
np.linspace(0, 10, 50)

array([  0.        ,   0.20408163,   0.40816327,   0.6122449 ,
         0.81632653,   1.02040816,   1.2244898 ,   1.42857143,
         1.63265306,   1.83673469,   2.04081633,   2.24489796,
         2.44897959,   2.65306122,   2.85714286,   3.06122449,
         3.26530612,   3.46938776,   3.67346939,   3.87755102,
         4.08163265,   4.28571429,   4.48979592,   4.69387755,
         4.89795918,   5.10204082,   5.30612245,   5.51020408,
         5.71428571,   5.91836735,   6.12244898,   6.32653061,
         6.53061224,   6.73469388,   6.93877551,   7.14285714,
         7.34693878,   7.55102041,   7.75510204,   7.95918367,
         8.16326531,   8.36734694,   8.57142857,   8.7755102 ,
         8.97959184,   9.18367347,   9.3877551 ,   9.59183673,
         9.79591837,  10.        ])

### eye

Creates an identity matrix.

In [14]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

## Random

Numpy also has lots of ways to create random number arrays.

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [15]:
np.random.rand(2)

array([ 0.77933343,  0.59125177])

In [16]:
np.random.rand(5, 5)

array([[ 0.84836712,  0.90651772,  0.59895401,  0.18970404,  0.33418152],
       [ 0.88764409,  0.54646169,  0.7624808 ,  0.00763172,  0.40958152],
       [ 0.67738622,  0.77298993,  0.00640307,  0.84269618,  0.40185814],
       [ 0.12748651,  0.66076388,  0.45038329,  0.19741733,  0.53639267],
       [ 0.43021004,  0.60516436,  0.92372331,  0.93340228,  0.92785022]])

### randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform.

In [17]:
np.random.randn(2)

array([-0.65972311, -0.9440729 ])

In [18]:
np.random.randn(5, 5)

array([[-0.45853212,  0.78313099,  0.19216579, -0.67967872,  1.28287447],
       [-0.2538602 , -0.30957829,  0.02350284, -0.79776879,  0.02369725],
       [ 1.319343  , -0.69083976, -0.55240905,  0.41600287,  0.11711922],
       [ 2.02300526,  0.01153108,  0.52080911,  0.81014879, -0.98252813],
       [ 0.00271665,  1.85146236,  0.36778845,  0.27165314,  0.75624227]])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [19]:
np.random.randint(1, 100)

71

In [20]:
np.random.randint(1, 100, 10)

array([61, 93, 80,  7, 87, 17, 89, 57, 11, 43])

## Array Attributes and Methods


In [21]:
arr = np.arange(25)
ranarr = np.random.randint(0, 50, 10)

In [22]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [23]:
ranarr

array([18, 37, 33, 21,  6,  8, 49,  0, 25, 12])

### Reshape

Returns an array containing the same data with a new shape.

In [24]:
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

We need to have all elements to fill reshaped array.

In [25]:
arr.reshape(5, 10)

ValueError: total size of new array must be unchanged

### max, min, argmax, argmin

These are useful methods for finding max or min values. 

Or to find their index locations using argmin or argmax.

In [26]:
ranarr

array([18, 37, 33, 21,  6,  8, 49,  0, 25, 12])

In [27]:
ranarr.max()

49

In [28]:
ranarr.argmax()

6

In [29]:
ranarr.min()

0

In [30]:
ranarr.argmin()

7

### Shape

Shape is an attribute that arrays have (not a method).

In [31]:
# Vector.
arr.shape

(25,)

In [32]:
# Notice the two sets of brackets.
arr.reshape(1, 25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24]])

In [33]:
arr.reshape(1, 25).shape

(1, 25)

In [34]:
arr.reshape(25, 1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [35]:
arr.reshape(25, 1).shape

(25, 1)

### dtype

You can also grab the data type of the object in the array.

In [36]:
arr.dtype

dtype('int64')

# NumPy Indexing and Selection

In this lecture we will discuss how to select elements or groups of elements from an array.

In [37]:
# Creating sample array.
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Bracket Indexing and Selection
The simplest way to pick one or some elements of an array looks very similar to Python lists.

In [38]:
# Get a value at an index.
arr[8]

8

In [39]:
# Get values in a range.
arr[0:5]

array([0, 1, 2, 3, 4])

In [40]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [41]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

## Broadcasting

Numpy arrays differ from a normal Python list because of their ability to broadcast.

In [42]:
# Setting a value with index range (Broadcasting).
# We broadcast 100 to all the elements selected.
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

## Views

In [43]:
# Reset array, we'll see why I had to reset in a moment.
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [44]:
# Important notes on slices.
slice_of_arr = arr[0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [45]:
# Change slice using broadcasting.
slice_of_arr[:] = 99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [46]:
# Now note the changes also occur in our original array!
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

Data is not copied, it's a view of the original array! This avoids memory problems!

To get a copy, need to be explicit.

In [47]:
arr_copy = arr.copy()
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

## Indexing a 2D array (matrices)

### General indexing

The general format is **arr_2d[row][col]** or **arr_2d[row, col]**. 

Recommended usually is using the comma notation for clarity.

In [48]:
arr_2d = np.array(([5, 10, 15], [20, 25, 30], [35, 40, 45]))
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [49]:
# Indexing row.
arr_2d[0]

array([ 5, 10, 15])

In [50]:
# Getting individual element value.
arr_2d[0][0] # row column

5

In [51]:
# Getting individual element value - better notation!
arr_2d[2, 1] # row column

40

In [52]:
# 2D array slicing.

# Shape (2,2) from top right corner.

arr_2d[:2, 1:] # row column

array([[10, 15],
       [25, 30]])

In [53]:
arr_2d[1:, 1:] # row column

array([[25, 30],
       [40, 45]])

In [54]:
# Shape bottom row.
arr_2d[2]

array([35, 40, 45])

In [55]:
# Shape bottom row.
arr_2d[2, :]

array([35, 40, 45])

### Fancy Indexing

Fancy indexing allows you to select entire rows or columns out of order.

In [56]:
arr_2d = np.zeros((10, 10))
arr_2d

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [57]:
# Length of array.
arr_length = arr_2d.shape[1]
arr_length

10

In [58]:
# Set up an array.
for i in range(arr_length):
    arr_2d[i] = i
    
arr_2d

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.],
       [ 9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.]])

In [59]:
# Selecting non-consecutive rows.
arr_2d[[2, 4, 6, 8]]

array([[ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.]])

In [60]:
# In any order.
arr_2d[[6, 4, 2, 7]]

array([[ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.]])

## More Indexing Help
Indexing a 2d matrix can be a bit confusing at first, especially when you start to add in step size. Try google image searching NumPy indexing to fins useful images, like this one:

<img src= 'http://memory.osu.edu/classes/python/_images/numpy_indexing.png' width=500/>

## Conditional selection

Let's briefly go over how to use brackets for selection based off of comparison operators.

In [61]:
arr = np.arange(1, 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [62]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,  True], dtype=bool)

In [63]:
bool_arr = arr > 4
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,  True], dtype=bool)

In [64]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [65]:
arr[arr > 4]

array([ 5,  6,  7,  8,  9, 10])

In [66]:
x = 2
arr[arr > x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

## Practice slicing

Try to select random ranges from it.

In [67]:
arr_2d = np.arange(50).reshape(5, 10)
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

# NumPy Operations

## Arithmetic - Array with Array


In [68]:
arr = np.arange(0, 10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [70]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [71]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [72]:
# Warning on division by zero, but not an error!
# Just replaced with nan.
arr / arr

//anaconda/lib/python3.6/site-packages/ipykernel/__main__.py:3: RuntimeWarning: invalid value encountered in true_divide
  app.launch_new_instance()


array([ nan,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.])

In [73]:
# Also warning, but not an error instead infinity.
1 / arr

//anaconda/lib/python3.6/site-packages/ipykernel/__main__.py:2: RuntimeWarning: divide by zero encountered in true_divide
  from ipykernel import kernelapp as app


array([        inf,  1.        ,  0.5       ,  0.33333333,  0.25      ,
        0.2       ,  0.16666667,  0.14285714,  0.125     ,  0.11111111])

In [74]:
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

## Arithmetic - Array with Scalars


In [75]:
arr * 10

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

## Errors in NumPy

In [76]:
# Python throws error.
1 / 0

ZeroDivisionError: division by zero

In [77]:
# NumPy gives warnings and replaces values with nan or inf.

arr / arr

//anaconda/lib/python3.6/site-packages/ipykernel/__main__.py:3: RuntimeWarning: invalid value encountered in true_divide
  app.launch_new_instance()


array([ nan,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.])

## Universal Array Functions

Numpy comes with many [universal array functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), which are essentially just mathematical operations you can use to perform the operation across the array.

In [78]:
# Square root.
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ])

In [79]:
# Exponential (e^)
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03])

In [80]:
np.max(arr)

9

In [81]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [82]:
np.log(arr)

//anaconda/lib/python3.6/site-packages/ipykernel/__main__.py:1: RuntimeWarning: divide by zero encountered in log
  if __name__ == '__main__':


array([       -inf,  0.        ,  0.69314718,  1.09861229,  1.38629436,
        1.60943791,  1.79175947,  1.94591015,  2.07944154,  2.19722458])